In [6]:
from PIL import Image
from numpy import genfromtxt
import gzip
import _pickle
from glob import glob
import numpy as np
import pandas as pd
import imageio

In [18]:
img=imageio.imread("train/drop-0.png", pilmode='RGB')
print(img.shape)
print(img)

(32, 32, 3)
[[[ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]
  ...
  [ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]]

 [[ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]
  ...
  [ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]]

 [[ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]
  ...
  [ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]]

 ...

 [[ 3  0 11]
  [17  4 32]
  [45 13 45]
  ...
  [25  8 30]
  [27  9 30]
  [12  4 18]]

 [[83 35 64]
  [92 43 62]
  [69 30 51]
  ...
  [15  5 25]
  [37 13 35]
  [30 10 31]]

 [[30 15 20]
  [34 20 21]
  [32 16 21]
  ...
  [ 6  2 14]
  [12  4 16]
  [10  3 14]]]


In [25]:
df = pd.read_csv("train.csv", names = ["class"])
np.array(df["class"]).shape

(2760,)

In [21]:
def dir_to_dataset(glob_files, loc_train_labels=""):
    print("Gonna process:\n\t %s"%glob_files)
    dataset = []
    for file_count, file_name in enumerate( sorted(glob(glob_files),key=len) ):
        img=imageio.imread(file_name, pilmode='RGB')
        #print(img.shape)
        #pixels = [f[0] for f in list(img.getdata())]
        dataset.append(img)
        if file_count % 1000 == 0:
            print("\t %s files processed"%file_count)
    # outfile = glob_files+"out"
    # np.save(outfile, dataset)
    if len(loc_train_labels) > 0:
        df = pd.read_csv(loc_train_labels, names = ["class"])
        return np.array(dataset), np.array(df["class"])
    else:
        return np.array(dataset)
    
Data1, y1 = dir_to_dataset("train/*.png","train.csv")
Data2, y2 = dir_to_dataset("valid/*.png","valid.csv")
Data3, y3 = dir_to_dataset("test/*.png","test.csv")

# Data and labels are read 
train_num = 2758
valid_num = 844
test_num = 420

train_set_x = Data1[:train_num]
train_set_y = y1[1:train_num+1]
val_set_x = Data2[:valid_num]
val_set_y = y2[1:valid_num+1]
test_set_x = Data3[:test_num]
test_set_y = y3[1:test_num+1]

Gonna process:
	 train/*.png
	 0 files processed
	 1000 files processed
	 2000 files processed
Gonna process:
	 valid/*.png
	 0 files processed
Gonna process:
	 test/*.png
	 0 files processed


In [29]:
# Divided dataset into 3 parts. I had 7717 images for training, 1653 images for validation and 1654 images for testing

train_set = train_set_x, train_set_y
val_set = val_set_x, val_set_y
test_set = test_set_x, test_set_y

dataset = [train_set, val_set, test_set]

f = gzip.open('soundee.pkl.gz','wb')
_pickle.dump(dataset, f, protocol=2)
f.close()

In [28]:
len(val_set[0])

844